### ISSUE TITLE
Generador del mapa

### ISSUE THREAD

**Issue by pol-rivero** [proflolo/phantasia#1]
¡Buenas!
En uno de los streams mencionaste que estabas abierto a aceptar propuestas para el código generador del mapa.
No he podido encontrar ninguna dirección de email, así que he pensado en compartir mi propuesta aquí.

**Repo en Github:** https://github.com/p-rivero/SimpleMapGenerator

La idea es generar un laberinto usando un [recursive backtracker](https://weblog.jamisbuck.org/2010/12/27/maze-generation-recursive-backtracking) modificado (adaptado para funcionar sobre una matriz de booleanos, hay más info en el [readme](https://github.com/p-rivero/SimpleMapGenerator#how-it-works)).
Una vez hemos generado el laberinto, podemos eliminar algunas paredes para que sea más fácil de navegar. Esto se hace en un pase sobre la matriz resultado: si una pared se considera candidata, tiene una probabilidad de ser eliminada.

Es una class en C++ que hice una tarde, así que puede que sea bastante mejorable. En concreto:
- Usa la stdlib, pero no debería ser complicado traducirlo a C#.
- El grueso de los muros del laberinto siempre es de 1 tile.
- Y el problema más importante: el tamaño del tablero **siempre** debe ser impar, debido a un mapeo que hace el algoritmo. En el readme se explica el porqué.

Espero que resulte de ayuda!

**Comment by pol-rivero** [comment]
En el último stream has dicho que estas interesado en implementar un algoritmo de laberintos pero no te han contestado al correo. 
Si te refieres a éste, yo no he recibido ningún correo.

**Comment by proflolo** [comment]
Hola,

Pues sí que me refería a este… no entiendo por qué no lo recibisteis…

Este fue mi mensaje:

Pues la verdad es que pinta que encaja muy bien con al sistema que está
montado en el juego. Es cierto que tendría que convertirlo a C#, pero eso
no debería ser un problema. Por la limitación de que sea impar, tampoco lo
veo complicado, puedo adaptar el juego para que sea así siempre.

Entonces, si te parece bien, lo integraré en el proyecto, tanto de Unity
como de Unreal (que está ligeramente desactualizado, pero sigue ahí). No
creo que pueda hacerlo esta semana, pero de cara al stream del 25 sería un
buen candidato.

¿Querrás que te mencione durante la transmisión? Y si es así, ¿de qué forma
(nick, nombre...)? ¿Y de cara a los créditos (que algún día pondré... pero
estoy hablando de dentro de un año al menos)?

¡Muchas gracias!

Lolo

**Comment by p-rivero** [comment]
Buenas, tienes permiso para usarlo de la forma que quieras. En caso que decidas mencionarme (ya sea en stream o en los créditos), puedes hacerlo con un link a la repo original (https://github.com/p-rivero/SimpleMapGenerator) o con mi usuario de Twitch (_SaltPeppah_).
Suelo pasarme a menudo por el stream, así que si el código tiene muchos bugs ya sabrás a quien culpar 😉.
